@startuml
'https://plantuml.com/class-diagram

Note "TODO: UI classes" as N1

interface ServerApi
class serverListener
class ClientLogic

serverListener ..> ServerApi : implements
ClientLogic ..> ServerApi : uses

interface ServerApi{
    +connect(address : String, port : Port)
    +joinGame(roomNumber : int)
    +setRead(ready : boolean
    +moveChecker(oldX, oldY, newX, newY) : void
    +getColor() : void
    +getBoard() : Array<Array<Color>>
    +wait() : void
}

@enduml