@startuml
'https://plantuml.com/class-diagram

note "This interface allows interacting with the board. \n The implementation should check if the move is possible, \n but doesn't need to check neither who's made the move nor the win conditions" as BoardNote
note "This interface allows to interact with the game itself. \n It should check win cons and move correctness" as GMnote
note "Used for player distinction. \n The values' names may be considered symbolic" as ClNote
note "Used for seat distinction" as Snote

GMnote .. GameMaster
BoardNote .. Board
ClNote .. Color
Snote .. Seat

interface ServerApi
interface Board
interface Runnable
class Checker
class Server
class ArrayBoard
class SimpleMaster
class GameMaster
class Lobby
enum Color
enum Seat

Server ..|> ServerApi : implements
Color "1" --* "*" ArrayBoard
ArrayBoard ..|> Board : implements
Lobby ..> GameMaster : uses
SimpleMaster ..|> GameMaster : implements
SimpleMaster ..> Board : uses
Seat --o SimpleMaster : uses
Lobby "*" --* "1" Server
Player "0..6" --o Lobby
Player "*" --o Server
Player ..|> Runnable : implements

class Checker{
   + color : enum
}

class Player{
    -isReady : boolean
    -name : String
    -InterpretCommand() : void
    -moveChecker(oldX : int, oldY : int, newX : int, newY : int)  : void
    -setReady(isReady : boolean) : void
    -leave() : void
    -joinLobby(int number) : void
    -sendBoard() : void
    -CheckColor() : void
    +getName() : String
    +getReady() : boolean
}
class ArrayBoard{
    -colorList : Array<Array<Color>>
}

interface Board{
    +moveChecker(oldX : int, oldY : int, newX : int, newY : int) : boolean
    +getCheckerColor(X : int, Y : int) : Color
    +addChecker(X : int, Y : int, color : Color) : void
    +removeChecker(X : int, Y : int) : void
    +getCheckerColorArray() :  Array<Array<Color>>
}

interface GameMaster{
    __Meta methods__
   + addPlayer() : Color
   + addPlayer(seat : Seat) : Color
   + removePlayer(color : Color)
   + clearBoard() : void
   + startGame() : Color
   + isFinished() : Color
   __Game methods__
   + moveChecker(oldX : int, oldY : int, newX : int, newY : int, color : Color) : boolean
   + getCheckerArray() : Array<Array<Color>>
}
'For further consideration
interface ServerApi{
    kickPlayer(String name) : void
    showPlayers(String name) : Array<String>
    showPlayerCount() : int
}
class SimpleMaster{
    -board : Board
    -colorList : map<Seat,Color>
    -checkWinConditions(color : Color)r) : boolean
}
class Lobby{
    -game : GameMaster
    -colorMap : map<Player,Color>
    +removePlayer() : void
    +addPlayer() : void
    +getCurrentPlayerNumber() : Integer
    +getCheckerArray() : Array<Array<Integer>>
    +moveChecker(oldX : int, oldY: int, newX: int, newY : int, player : Player)
}
class Server{
    lobbies : LinkedList<Lobby>
    players : LinkedList<Player>
    interpretCommand()
}
enum Color{
    RED
    GREEN
    BLUE
    CYAN
    MAGENTA
    YELLOW
}
enum Seat{
    NORTH,
    SOUTH,
    NORTHEAST,
    NORTHWEST,
    SOUTHEAST,
    SOUTHWEST
}

@enduml