@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> WaitingForTurn

state Turn {
  [*] --> ChooseChecker
  ChooseChecker --> CanItMove
  CanItMove --> ChooseChecker : No
  CanItMove --> Move : Yes
  Move --> HopOneTile
   Move --> HopOver : CanItHopOver
   HopOneTile --> [*] : DidYouWin
   HopOver --> [*] : DidYouWin
  HopOneTile --> WaitingForTurn : EndTurn
  HopOver --> HopOver : CanItHopOver
  HopOver --> WaitingForTurn : EndTurn
}
state WaitingForTurn {
  [*] --> Idle
  Idle --> [*] : SomeoneElseWon
  Idle --> Turn : StartOfTurn
}
@enduml