@startuml
'https://plantuml.com/use-case-diagram

:User: as user
(Join a game) as (join)
(Leave game) as (leave)
(Make a move) as (move)
(Surrender) as (surr)
user --> join
user --> leave
user --> move
user --> surr
@enduml